### ISSUE TITLE
Short options and commands would be nice

### ISSUE THREAD

**Issue by kseistrup** [DanielVZ96/tzar#2]
E.g.,

```
  -h, --help
```

and

```
  compress, c
  extract, x
  list, l
```

And `-V, --version` would be convenient, too.

Cheers.

**Comment by DanielVZ96** [comment]
Yeah, they look handy. I'll try to implement them today at lunch.

**Comment by DanielVZ96** [comment]
~Done!~ 
![Screenshot from 2021-08-19 09-01-37](https://user-images.githubusercontent.com/19278837/130072975-830fd381-125a-471f-aaba-0f40f7a07cc9.png)

whoops, I forgot `-h`. I'll add that in any future update with features.

**Comment by kseistrup** [comment]
Looks great — thanks!

**Comment by DanielVZ96** [comment]
Done here: https://github.com/DanielVZ96/tzar/commit/47ab4d8ecbf0535c02240692b617f63b5ec92c6e

```
❯ tzar
Usage: tzar [OPTIONS] COMMAND [ARGS]...

Options:
  -V, --version  Show the version and exit.
  -h, --help     Show this message and exit.

Commands:
  compress
  extract
  list

  Tip: You can run any subcommand by only using it's first letter(s). E.g.
  instead of `extract`, just `e`, `ex`, `ext`, etc.
```

**Comment by kseistrup** [comment]
Sweet!
