### ISSUE TITLE
file extension not recognized if "file.1.zip"

### ISSUE THREAD

**Issue by rnonymous** [DanielVZ96/tzar#3]
Had the following interaction:

```
$ tzar extract thetvdb_6.0.0.0.zip .
No command found for that file extension.
$ mv thetvdb_6.0.0.0.zip thetvdb_6000.zip
$ tzar extract thetvdb_6000.zip .
Running: unzip thetvdb_6000.zip -d .
```

**Comment by DanielVZ96** [comment]
Hey, thanks for the heads up. I had a hunch that I'd have problems with multiple suffixes.

Fixed here: https://github.com/DanielVZ96/tzar/commit/282cdfaf00646c896a53a7f039c06191dd12ab00
