### ISSUE TITLE
extract to current dir?

### ISSUE THREAD

**Issue by drewauff** [DanielVZ96/tzar#5]
Seems  extracting to current dir does not work or is not available?

 I want to make a fzf/zle script but it will be much easier if when extracting and no dir is given then a dir is created in the current dir using the filename of the archive being used.

The script I have in mind will list only (all) archives in the current dir, select the archive hit enter and it extracts. simple.

Also how did you get the progress bar?

edit: just realised that was not a progress bar in your gif..but that would be an awesome addition :)

**Comment by DanielVZ96** [comment]
That's a nice and simple feature. I implented it here: https://github.com/DanielVZ96/tzar/commit/47ab4d8ecbf0535c02240692b617f63b5ec92c6e

You can upgrade tzar now to use it.

For example you can use `tzar extract name.zip` and it will extract the file to `name/` and create the directory in case it doesn't exist.

**Comment by drewauff** [comment]
Thank you! it works.. I just have to find a way tom implement a progress bar as an alternative to spewing out line after line of files etc. .. make a lot of sense for large archive.

I didn't check, but can DMG's be extracted with tzar?

**Comment by DanielVZ96** [comment]
Not currently but I'll add them later today to the default config file

**Comment by drewauff** [comment]
very much looking forward to this...just decompressed 6 archives in containing approx. 5000 files..so yeah..
